-- MySQL Workbench Synchronization
-- Generated: 2020-11-19 21:39
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: dhreg

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `Opportunities` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `Opportunities`.`interns` (
  `internID` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(40) NULL DEFAULT NULL,
  `password_md5` VARCHAR(32) NULL DEFAULT NULL,
  `first` VARCHAR(40) NULL DEFAULT NULL,
  `last` VARCHAR(40) NULL DEFAULT NULL,
  PRIMARY KEY (`internID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `Opportunities`.`opportunities` (
  `opportunityID` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `company` VARCHAR(40) NULL DEFAULT NULL,
  `city` VARCHAR(25) NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `position` VARCHAR(30) NULL DEFAULT NULL,
  `description` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`opportunityID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `Opportunities`.`assigned_opportunities` (
  `opportunityID` SMALLINT(6) NULL DEFAULT NULL,
  `internID` SMALLINT(6) NULL DEFAULT NULL,
  `date_selected` DATE NULL DEFAULT NULL,
  `date_approved` DATE NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
